In [ ]:
# Assessing geospatial distribution of population statistics.

Script to include :
 - external modules imported at the beginning of the script
 - functions that have been written to help ensure code is readable and reproducable - include docstring - explanation, different input parameters, and outputs
 - embedded comments
 -

In [10]:
# external modules:
import os # Review
import pandas as pd
import geopandas as gpd
import shapely
#import cartopy
#import pyepsy
#import rasterstats

#import matplotlib.pyplot as plt
#plt.ion() # make the plot interactive

Import Data
- Census data csv
- Data zone shapefile

In [11]:
zones = gpd.read_file('data_files/DZ2021.shp') # import data zones shapefile as zones
census = pd.read_csv('data_files/Census.csv') # import census data csv file as census

Join Census Data to Data Zones
DZ_2021_Code from census will join with DZ2021_cd from zones

In [8]:
zones.head() # identify header that will join with census data

,DZ2021_cd,DZ2021_nm,LGD2014_nm,Area_ha,Perim_km,geometry
0,N20000001,Dunsilly_A1,Antrim and Newtownabbey,2070.68,22.93,"POLYGON ((319580.264 396993.361, 319573.665 39..."
1,N20000002,Dunsilly_B1,Antrim and Newtownabbey,1253.69,19.14,"POLYGON ((323772.447 393378.876, 323764.289 39..."
2,N20000003,Dunsilly_A2,Antrim and Newtownabbey,792.91,15.50,"POLYGON ((305377.841 395055.242, 305378.841 39..."
3,N20000004,Dunsilly_A3,Antrim and Newtownabbey,1100.52,17.90,"POLYGON ((311500.959 395028.333, 311510.728 39..."
4,N20000005,Dunsilly_B2,Antrim and Newtownabbey,1740.82,21.93,"POLYGON ((323772.447 393378.876, 323784.201 39..."

In [12]:
census.head() # identify header that will join with census data

,ID,DZ_2021_Code,DZ_2021_Name,popn,le_4_yrs,PC_le_4_yrs,ge_66_yrs,PC_ge_66_yrs,working_age,employed,unemployed,PC_no_qual,PC_rented,PC_depriv_hholds,LTHC,PC_LTHC
0,1,N20000001,Dunsilly_A1,738,50,6.8,105,14.23,468,395,11,19.46,7.6,12.4,221,29.95
1,2,N20000002,Dunsilly_B1,331,9,2.7,65,19.64,211,187,6,14.69,13.5,18.9,109,32.93
2,3,N20000003,Dunsilly_A2,364,17,4.7,80,21.98,215,185,9,19.41,14.8,20.3,108,29.67
3,4,N20000004,Dunsilly_A3,663,31,4.7,112,16.89,381,324,12,14.40,10.9,12.3,193,29.15
4,5,N20000005,Dunsilly_B2,676,29,4.3,120,17.75,421,353,10,16.99,8.7,15.7,205,30.33

In [19]:
def joincsvtoshapefile(csvpath: str, shapefilepath: str, csvcolumn: str, shapefile_column: str):
    """
    Function to join columns in a CSV file to shapefile data using town names.
Parameters:
- csv_path: str
    The file path of the CSV file.
- shapefile_path: str
    The file path of the shapefile.
- csv_column: str
    The name of the column in the CSV file that contains the data zone.
- shapefile_column: str
    The name of the column in the shapefile that contains the data zone.

Returns:
- geopandas.GeoDataFrame:
    A GeoDataFrame with the joined data.

Raises:
- FileNotFoundError:
    If either the CSV file or the shapefile is not found.
"""
censuszones = joincsvtoshapefile(census, zones, DZ_2021_Code, DZ2021_cd) # join census data to data zones to give census geometry

## 'DZ_2021_Code' not defined - need to figure out how to define it!

NameError: name 'DZ_2021_Code' is not defined

Population Density

In [ ]:
# population density
# crs metric - ITM
# calculate area of data zones
# calulcate population density
# error check?

In [9]:
zones.crs # checking coordinate system is Irish Transverse Mercator, ESPG: 29902
# if not
# zones = zones.to_crs(epsg=29902)

<Projected CRS: EPSG:29902>
Name: TM65 / Irish Grid
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Ireland - onshore.
- bounds: (-10.56, 51.39, -5.93, 55.43)
Coordinate Operation:
- name: Irish Grid
- method: Transverse Mercator
Datum: TM65
- Ellipsoid: Airy Modified 1849
- Prime Meridian: Greenwich

In [ ]:
# create map of popdensity per data zone

Website to determine UTM zone: https://mangomap.com/robertyoung/maps/69585/what-utm-zone-am-i-in-#

In [ ]:
ni_utm = ccrs.UTM(29) #Universal Transverse Mercator reference system Northern Ireland lies in zone 29

Unemployment

In [ ]:
# unemployment rate 
# use economically active - unemployed / (employed + unemployed) * 100

In [ ]:
# map of unemployment rate per data zone